Proyecto vacunacion/Controllers/VentaProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto_vacunacion.Models;
using System.Data;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Session;
using Newtonsoft.Json;


namespace Proyecto_vacunacion.Controllers
{
    public class VentaProductoController : Controller
    {


        string cadena = @"server = DESKTOP-7IQJ2J4\SQLEXPRESS;database = TIENDA;Trusted_Connection = True;" +
          "MultipleActiveResultSets = True;TrustServerCertificate = False;Encrypt = False";

        
        public ActionResult Principal()
        {
            return View();
        }

        public ActionResult Comprar()
        {
            if (HttpContext.Session.GetString("carrito") == null)
            {
                return RedirectToAction("Principal");
            }

            var carrito = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("carrito"));
            ViewBag.monto = carrito.Sum(p => p.subtotal);
            return View(carrito);


        }

        //LISTA PRODUCTO POR JSAON **
        public ActionResult ListaProducto()
        {
            using (SqlConnection cn = new SqlConnection(cadena))
            {          
            
                List<ProductoO> aProductos = new List<ProductoO>();
            SqlCommand cmd = new SqlCommand("SP_LISTAPRODUCTOS", cn);
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aProductos.Add(new ProductoO()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString(),
                    descripcion = dr[2].ToString(),
                    precio = double.Parse(dr[3].ToString()),
                    stockActual = int.Parse(dr[4].ToString()),
                    categoria = dr[5].ToString(),
                    proveedor = dr[6].ToString(),
                    foto = dr[7].ToString()

                });
            }
            dr.Close();
            cn.Close();
            return Json(aProductos);    
            
            }

        }

        //LISTA PRODUCTO **
        List<ProductoO> ListProductos()
        {

            using (SqlConnection cn = new SqlConnection(cadena))
            {

                List<ProductoO> aProductos = new List<ProductoO>();
                SqlCommand cmd = new SqlCommand("SP_LISTAPRODUCTOS", cn);
                cn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    aProductos.Add(new ProductoO()
                    {
                        codigo = int.Parse(dr[0].ToString()),
                        nombre = dr[1].ToString(),
                        descripcion = dr[2].ToString(),
                        precio = double.Parse(dr[3].ToString()),
                        stockActual = int.Parse(dr[4].ToString()),
                        categoria = dr[5].ToString(),
                        proveedor = dr[6].ToString(),
                        foto = dr[7].ToString()
                    });
                }
                dr.Close();
                cn.Close();
                return aProductos;

            }
        }

        //VISTA DE PRODUCTO SELECCIONADO **
        public ActionResult seleccionaProductos(int id)
        {

            if (HttpContext.Session.GetString("carrito")== null)
            {
                HttpContext.Session.SetString("carrito",JsonConvert.SerializeObject(new List<Item>()));
            }

            ProductoO objP = ListProductos().Where(a => a.codigo == id).FirstOrDefault();
            return View(objP);

        }

        //VISTA DE AGREGAR PRODUCTO SELECCIONADO A SESSION**
        public ActionResult agregarProducto(int id, int cant = 0)
        {
            var miProducto = ListProductos().Where(p => p.codigo == id).FirstOrDefault();
            Item objI = new Item()
            {
                codigo = miProducto.codigo,
                nombre = miProducto.nombre,
                descripcion = miProducto.descripcion,
                precio = miProducto.precio,
                cantidad = cant,
                foto = miProducto.foto
            };


            var miCarrito = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("carrito"));
            miCarrito.Add(objI);

            HttpContext.Session.SetString("carrito", JsonConvert.SerializeObject(miCarrito));
            return RedirectToAction("Principal");
        }

        //METODO PARA LISTAR LOS PRODUCTOS SELECCIONADOS PARA EL CARRITO **
        public ActionResult ListaItem()
        {

            if (HttpContext.Session.GetString("carrito") == null)
            {
                return RedirectToAction("Principal");
            }
            var carrito = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("carrito"));
            var monto = carrito.Sum(p => p.subtotal);

            return Json(carrito);


        }

        public ActionResult actualizarTotal()
        {
            if (HttpContext.Session.GetString("carrito") == null)
            {
                return RedirectToAction("Principal");
            }
            var carrito = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("carrito"));
            var monto = carrito.Sum(p => p.subtotal);

            return Json(monto);

        }

        public ActionResult eliminaProducto(int? id = null)
        {

            if (id == null) return RedirectToAction("carritoCompras");
            var carrito = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("carrito"));
            var item = carrito.Where(i => i.codigo == id).FirstOrDefault();
            carrito.Remove(item);
            HttpContext.Session.SetString("carrito", JsonConvert.SerializeObject(carrito));

            return Json(carrito);
        }

        //Metodo para pagar
        public ActionResult Pago()
        {
            List<Item> detalle = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("carrito"));
            double mt = 0;
            foreach (Item it in detalle)
            {
                mt += it.subtotal;
            }
            ViewBag.mt = mt;
            return View(detalle);
        }

        public ActionResult Final(string dni, string nombres)
        {
            ViewBag.dni = dni;
            ViewBag.nombres = nombres;
            List<Item> detalle = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("carrito"));
            double mt = 0;
            foreach (Item it in detalle)
            {
                mt += it.subtotal;
            }
            ViewBag.mt = mt;
            return View();
        }






    }
}

Proyecto vacunacion/Views/VentaProducto/Comprar.cshtml
@model IEnumerable<Proyecto_vacunacion.Models.Item>

@{
    ViewBag.Title = "Comprar";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}


<link href="~/css/comprar.css" rel="stylesheet" />




<div id="container" class="container col-md-11">

    <div class="row" id="row">
        <div id="productos" class="col-sm-9">

        </div>


        <div id="compra" class="col-sm-3 p-2">
            <div class="card my-2 h-auto">

                <div class="card-header">
                    <h3>Generar Compra</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label class="">SubTotal:</label>
                        <input class="form-control" type="text" name="name" id="sub" value="" readonly />
                    </div>



                    <div class="form-group">
                        <label class="">Total a Pagar:</label>
                        <input class="form-control" type="text" name="name" id="total" value="" readonly />
                    </div>



                </div>
                <div class="card-footer">
                    <span class="my-">
                        @Html.ActionLink("Seguir comprando", "Principal", "VentaProducto",  new { @class = "btn btn-success btn-block" })
                        <button id="pagarTodo" onclick="PagarTodo();" class="btn btn-danger btn-block p-2">Pagar</button>
                    </span>
                    <br />

                    <p id="">


                    </p>



                </div>

            </div>
            <br />
            <br />
            <br />
        </div>


    </div>

    <h6 class="col-md-5">
    </h6>

</div>
<br />
<br />









<script>
    ListaItem();

    function ListaItem() {
        var cantidad = document.getElementById("sesion");
        var cantidad2 = document.getElementById("sesion2");


        fetch("/VentaProducto/ListaItem").
            then(response => response.json()).
            then(response => {

                let resultado = '';

                let totalPagar = '';


                console.log(response);
                for (let i in response) {

                    resultado += `


                             <div class="col-md-12 p-2">
                                 <div class="card my-2 h-auto">
                                    <div id="resultadoSeleccion" class="card-body">
                                         <input class="task-delete" taskId="" type="hidden" id="codPro" name="" value="${response[i].codigo}" />
                                         <div id="imgSeleccion">
                                         <img class="" src=${response[i].foto.slice(1)} alt="">
                                         </div>
                                         <div id="contenedorSeleccion">
                                          <div id="DescSeleccion">
                                           <span> ${response[i].nombre}</span>
                                           <a href="#" class="">${response[i].descripcion} </a>
                                          </div>
                                         <div id="precioSeleccion">
                                          <span class="">Precio: S/. ${response[i].precio}</span>
                                         </div>
                                         <div id="cantidadSeleccion">
                                        </div>
                                       </div>
                                       <div id="subtotal">
                                       <p>
                                       <button class="fas fa-trash-alt btn btn-danger" onclick="elimina(${response[i].codigo})"></button>
                                       </p>
                                       <p>
                                       <label for="cantidad">cantidad:</label>
                                       ${response[i].cantidad}
                                       </p>
                                       <p>
                                       <label for="subtotal">SubTotal:</label>
                                       S/. ${response[i].subtotal}
                                       </p>
                                 </div>
                             </div>
                           </div>
    </div>


                                    `
                }




                document.getElementById("productos").innerHTML = resultado;





            })
    }
    ActualizarMonto();
    function elimina(id) {

        fetch("eliminaProducto?id=" + id).
            then(response => response.json()).
            then(data => {

                ListaItem();
                ActualizarMonto();
                cargarItem();
            });
    }
    function ActualizarMonto() {

        fetch("actualizarTotal").
            then(response => response.json()).
            then(data => {
                console.log(data);
                document.getElementById("sub").value = 'S/. ' + data;

                document.getElementById("total").value = 'S/. ' + data;


            })


    }



    function PagarTodo() {

        Swal.fire(
            'Pago!',
            'Pagar por Paypal o Visa',
            'success'
        )
    }



</script>

    <script src="https://www.paypal.com/sdk/js?client-id=sb"></script>
<script>paypal.Buttons().render('h6');</script>

Proyecto vacunacion/Views/VentaProducto/Principal.cshtml
@{
    ViewBag.Title = "Principal";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}





<div class="container col-md-11">


    <div class="row" id="row">
        <div class="col-md-12 p-2">

            <div class="card my-2 h-auto">
                <div id="resultadoProducto" class="card-body">
                </div>
            </div>

           
        </div>
    </div>
</div>




<br>
<br>
<script>
    cargarProductos();
    
    function cargarProductos() {
        fetch("/VentaProducto/ListaProducto").
            then(response => response.json()).
            then(response => {
                let resultado = '';
               
                console.log(response);
                for (let i in response) {
                  
                    resultado += `<div id="imgSeleccion">

                            <a id="mienlace" href="seleccionaProductos/${response[i].codigo}">
                            <img id="" class="" src="${response[i].foto.slice(1)}" alt=""></a>
                            <p> ${response[i].nombre} <br> stockActual : ${response[i].stockActual} <br> S/. ${response[i].precio}</p>
                            
                        </div> `
                }

                document.getElementById("resultadoProducto").innerHTML = resultado;
                
            })
    };
    
    
</script>

Proyecto vacunacion/Views/VentaProducto/seleccionaProductos.cshtml
@model Proyecto_vacunacion.Models.ProductoO

@{
    ViewBag.Title = "seleccionaProducto";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}


<link href="~/css/seleccion.css" rel="stylesheet" />


<div class="container">
    <div class="row" id="row">
        <div class="col-md-12 p-2">
            <div class="card my-2 h-auto">

                <div id="resultadoSeleccion" class="card-body">
                    <input type="hidden" id="codPro" name="name" value="@Html.DisplayFor(model => model.codigo)" />
                    <div id="imgSeleccion">
                        <img id="" class="" src="@Url.Content(Model.foto)" alt="">
                    </div>
                    <div id="contenedorSeleccion">
                        <div id="DescSeleccion">
                            <p>@Html.DisplayFor(model => model.nombre)</p>
                            <a href="#" class="">
                                @Html.DisplayFor(model => model.descripcion)
                            </a>
                           
                        </div>
                        <div id="precioSeleccion">

                            <span class="">Precio: S/. @Html.DisplayFor(model => model.precio)</span>
                            <p>@Html.DisplayFor(model => model.stockActual) unidades disponibles</p>
                        </div>

                        
                        @using (Html.BeginForm("agregarProducto", "VentaProducto"))
                        {

                            @Html.Hidden("id", Model.codigo)
                    <div id="cantidadSeleccion">
                        <label for="cantidad">cantidad:</label>
                        <input type="number" name="cant" id="cantidad" value="1">
                       
                    </div>
                           
                      @Html.ActionLink("Regresar a tienda", "Principal", "VentaProducto", new { @class = "btn btn-primary" })
                            <input type="submit" value="Añadir al carrito" class="btn btn-danger" />

                        }


                    </div>

                </div>

            </div>


        </div>
    </div>
</div>